### ISSUE TITLE
ModuleNotFoundError: No module named 'git'

### ISSUE THREAD

**Issue by davidfoerster** [davidfoerster/aptsources-cleanup#10]
```
gelmo@gelmo-laptop:~/Downloads/aptsources/aptsources-cleanup-0.1.4$ sudo ./aptsources-cleanup 
Traceback (most recent call last):
  File "./aptsources-cleanup", line 9, in <module>
    runpy.run_module('aptsources_cleanup', run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 201, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/gelmo/Downloads/aptsources/aptsources-cleanup-0.1.4/src/aptsources_cleanup/__init__.py", line 33, in <module>
    __version__ = str(__version__())
  File "/home/gelmo/Downloads/aptsources/aptsources-cleanup-0.1.4/src/aptsources_cleanup/util/version/__init__.py", line 154, in get_version
    _version = version_info.load()
  File "/home/gelmo/Downloads/aptsources/aptsources-cleanup-0.1.4/src/aptsources_cleanup/util/version/__init__.py", line 101, in load
    return cls.from_repo(version)
  File "/home/gelmo/Downloads/aptsources/aptsources-cleanup-0.1.4/src/aptsources_cleanup/util/version/__init__.py", line 108, in from_repo
    import git
ModuleNotFoundError: No module named 'git'
```

Worked great from source after installing "python3-git". Ubuntu 18.04.

**Comment by davidfoerster** [comment]
That's a packaging bug coupled with an unnecessary module dependency. Fixed in release v0.1.5 and commit 4d41c2a02a6c1731f280bf582099e154ab4a783f respectively.
