### ISSUE TITLE
AttributeError: module 'aptsources_cleanup.util.collections' has no attribute 'Container'

### ISSUE THREAD

**Issue by alkhaldieid** [davidfoerster/aptsources-cleanup#17]
ran aptsources-cleanup.zip after getting the below error with apt update.
```
Hit:1 http://security.ubuntu.com/ubuntu trusty-security InRelease
Hit:2 http://es-mirrors.evowise.com/ubuntu disco InRelease                                                                                                                                                 
Hit:3 http://es-mirrors.evowise.com/ubuntu disco-updates InRelease                                                                                                                                         
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                               
Hit:5 http://es-mirrors.evowise.com/ubuntu disco-backports InRelease                                                                                                                              
Hit:6 http://es-mirrors.evowise.com/ubuntu disco-security InRelease                                                                                                                               
Hit:7 https://dl.winehq.org/wine-builds/ubuntu disco InRelease                                                                                                    
Hit:8 http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu disco InRelease                                                                  
Hit:9 http://dl.google.com/linux/chrome/deb stable Release                                                         
Hit:10 http://archive.canonical.com/ubuntu disco InRelease                                                              
Ign:12 http://ppa.launchpad.net/t-tujikawa/ppa/ubuntu disco InRelease                                                   
Err:13 http://ppa.launchpad.net/t-tujikawa/ppa/ubuntu disco Release                                              
  404  Not Found [IP: 91.189.95.83 80]
Hit:11 https://packagecloud.io/github/git-lfs/ubuntu disco InRelease
Reading package lists... Done
W: Target Sources (restricted/source/Sources) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:7
E: The repository 'http://ppa.launchpad.net/t-tujikawa/ppa/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Sources (restricted/source/Sources) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:7
```
running the following terminal command
`sudo python3 -OEs aptsources-cleanup.zip
`
produced the following error

```
Overlapping source entries:
 1. file “/etc/apt/sources.list”:
    deb-src http://es-mirrors.evowise.com/ubuntu/ disco main restricted #Added
    by software-properties
 2. file “/etc/apt/sources.list”:
    deb-src http://es-mirrors.evowise.com/ubuntu/ disco restricted multiverse
    universe
I disabled the latter entry.

1 source entry was disabled:
  # deb-src http://es-mirrors.evowise.com/ubuntu/ disco restricted multiverse
    universe

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "aptsources-cleanup.zip/__main__.py", line 8, in <module>
  File "/usr/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "aptsources-cleanup.zip/aptsources_cleanup/__main__.py", line 353, in <module>
  File "aptsoures-cleanup.zip/aptsources_cleanup/__main__.py", line 43, in main
  File "aptsources-cleanup.zip/aptsources_cleanup/__main__.py", line 283, in handle_duplicates
  File "aptsources-cleanup.zip/aptsources_cleanup/util/gettext.py", line 277, in __init__
    if self._fallback:
  File "aptsources-cleanup.zip/aptsources_cleanup/util/gettext.py", line 335, in _get_string_transformer
    
AttributeError: module 'aptsources_cleanup.util.collections' has no attribute 'Container'

```
using Ubuntu 19.04

I don't know what other system info are related.

**Comment by davidfoerster** [comment]
Thanks for your report!

Fixed in 0e9dc2a0f5b39c68b01541a6dbb52ce85e17aa02 and pushed in v0.1.6.1.
